#!/usr/bin/env bash
#nginx engine web starting


sudo apt update
sudo apt-get install nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
sudo ufw status
sudo apt-get install curl
curl -4 icanhazip.com
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
