#!/usr/bin/env bash
#this is for loop that has 4 bad luck 8 good luck and the rest best school

i=0

while ((i<10))
do
	if ((i==3))
	then
		echo "bad luck"
	elif((i==7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
